### ISSUE TITLE
"ctorParameters.map is not a function" error when the ContextMenuModule is imported

### ISSUE THREAD

**Issue by tomasklima** [isaacplmann/angular2-contextmenu#41]
As soon as I try to add the ContextMenuModule to imports of my module I get "ctorParameters.map is not a function" error. Has anybody encountered this problem before?

**Comment by isaacplmann** [comment]
I haven't seen this.  What version of angular are you using?

**Comment by tomasklima** [comment]
I have installed 2.0.1. Just I'm going to try to update...

**Comment by isaacplmann** [comment]
Apparently [other libraries have this issue too](https://github.com/SebastianM/angular2-google-maps/issues/812) when people are using < 2.3.1.

**Comment by tomasklima** [comment]
It's working after I upgraded the Angular to 2.4.3. Thanks @isaacplmann to pointing me!
